version: '3.7'

services:
  api:
    container_name: favo-de-mel-webapi
    build: .
    image: favo-de-mel-webapi:dev
    ports:
      - "5000:5000"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    networks: 
      - favo-de-mel-webapi

  sqlserver:
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@favodemel1234"
      ACCEPT_EULA: "Y"
    image: "mcr.microsoft.com/mssql/server:2017-latest"
      
networks:
  favo-de-mel-webapi:
    name: favo-de-mel-network
