version: '3.7'

services:
  api:
    container_name: favodemel-api
    build: .
    image: favodemel-api:dev
    ports:
      - "5000:5000"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
    networks: 
      - favodemel-api

  sqlserver:
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@favodemel1234"
      ACCEPT_EULA: "Y"
    image: "mcr.microsoft.com/mssql/server:2017-latest"
      
networks:
  favodemel-api:
    name: favodemel-network
