version: '3.7'

services:
  api:
    container_name: favodemel-api
    build: .
    image: favodemel-api:dev
    ports:
      - "5000:80"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - >-
          ConnectionStrings__favo-de-mel=Server=sqlserver;Initial Catalog=favodemel;User Id=SA;Password=@favodemel1234
    networks:
      - favodemel-network
    depends_on:
      - sqlserver

  sqlserver:
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "@favodemel1234"
      ACCEPT_EULA: "Y"
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    networks:
      - favodemel-network

networks:
  favodemel-network:
    name: favodemel-network
    driver: 'bridge'